using System.Collections.Generic;

namespace Lithiumvpn.Localization
{
    /// <summary>
    /// All user-facing strings, keyed by a stable identifier.
    /// Add a key to BOTH dictionaries when introducing new text.
    /// </summary>
    internal static class Strings
    {
        public static readonly Dictionary<string, string> En = new()
        {
            // ── Navigation ──
            ["Nav_Dashboard"] = "Dashboard",
            ["Nav_Configs"] = "Configs",
            ["Nav_Account"] = "Account",
            ["Nav_Coins"] = "Coins",
            ["Nav_Plans"] = "Plans",
            ["Nav_HelpTooltip"] = "Help & Tours",

            // ── Common ──
            ["Common_Next"] = "Next ›",
            ["Common_SkipTour"] = "Skip Tour",
            ["Common_Done"] = "Done ✓",
            ["Common_GotIt"] = "Got it",
            ["Common_Cancel"] = "Cancel",
            ["Common_OK"] = "OK",
            ["Common_Connect"] = "Connect",
            ["Common_Ping"] = "Ping",
            ["Common_TestPing"] = "Test ping",
            ["Common_Pinging"] = "Pinging…",
            ["Common_Open"] = "Open",

            // ── System tray ──
            ["Tray_Open"] = "Open LithiumVPN",
            ["Tray_Disconnect"] = "Disconnect",
            ["Tray_Exit"] = "Exit",

            // ── Countries ──
            ["Country_Netherlands"] = "Netherlands",
            ["Country_Germany"] = "Germany",
            ["Country_Poland"] = "Poland",

            // ── Settings ──
            ["Settings_Appearance"] = "Appearance",
            ["Settings_AppTheme"] = "App Theme",
            ["Settings_ThemeDesc"] = "Choose your preferred color theme",
            ["Settings_ThemeLight"] = "Light",
            ["Settings_ThemeDark"] = "Dark",
            ["Settings_ThemeSystem"] = "System",
            ["Settings_WindowEffect"] = "Window Effect",
            ["Settings_WindowEffectDesc"] = "Choose the window background effect",
            ["Settings_EffectMatte"] = "Matte",
            ["Settings_EffectHighMatte"] = "High Matte",
            ["Settings_EffectGlass"] = "Glass",
            ["Settings_EffectGlassThin"] = "Glass Thin",
            ["Settings_LanguageSection"] = "Language & Region",
            ["Settings_Language"] = "Language",
            ["Settings_LanguageDesc"] = "Choose your preferred display language",
            ["Settings_LanguageEnglish"] = "English",
            ["Settings_LanguagePersian"] = "فارسی",

            // ── Proxy exceptions ──
            ["Settings_ProxySection"] = "Proxy Exceptions",
            ["Settings_ProxyExceptions"] = "Bypass list",
            ["Settings_ProxyExceptionsDesc"] = "Domains or addresses added here are NOT sent through the VPN tunnel (they connect directly). Wildcards like *.example.com are supported. Changes apply immediately while connected.",
            ["Settings_ProxyAddPlaceholder"] = "e.g. *.mydomain.com or 192.168.1.5",
            ["Settings_ProxyAdd"] = "Add",
            ["Settings_ProxyEmpty"] = "No exceptions yet. Everything goes through the tunnel.",
            ["Settings_ProxyEdit"] = "Edit",
            ["Settings_ProxyDelete"] = "Delete",
            ["Settings_ProxySave"] = "Save",
            ["Settings_ProxyCancel"] = "Cancel",
            ["Settings_ProxyDuplicate"] = "That entry already exists.",

            // ── Dashboard ──
            ["Dash_GbLeft"] = "GB Left",
            ["Dash_Expiry"] = "Expiry",
            ["Dash_DaysLeft"] = "Days Left",
            ["Dash_Ping"] = "Ping",
            ["Dash_Upload"] = "Upload",
            ["Dash_Download"] = "Download",
            ["Dash_ChooseConfig"] = "Choose your configuration",
            ["Dash_NoConfigSelected"] = "No config selected",
            ["Dash_Tour1Title"] = "Server Config",
            ["Dash_Tour1Sub"] = "This shows your currently selected VPN server. Click the arrow button to change the server.",
            ["Dash_Tour2Title"] = "Connect Button",
            ["Dash_Tour2Sub"] = "Tap this button to connect or disconnect from your VPN. It turns green when connected.",
            ["Dash_Tour3Title"] = "Connection Stats",
            ["Dash_Tour3Sub"] = "These cards show your remaining data, days until expiry, current ping, and upload/download speeds.",
            ["Dash_SelectConfigFirst"] = "Select a config first, then connect.",
            ["Dash_ConnectFailed"] = "Connection failed: {0}",
            ["Dash_ConnectionLost"] = "The connection was lost.",
            ["Dash_SpeedTest"] = "Run speed test",
            ["Dash_SpeedTestNeedsConnection"] = "Connect to the VPN first to run a speed test.",
            ["Dash_SpeedTestUsesData"] = "Note: the speed test consumes some of your data quota.",

            // ── Servers / Configs ──
            ["Servers_Subscriptions"] = "Subscriptions",
            ["Servers_Active"] = "Active",
            ["Servers_Locations"] = "Locations",
            ["Servers_Purchases"] = "Purchases",
            ["Servers_Purchase1"] = "Purchase #1",
            ["Servers_Purchase2"] = "Purchase #2",
            ["Servers_PlanDetails"] = "Plan details",
            ["Servers_DataLeft"] = "Data left",
            ["Servers_TimeLeft"] = "Time left",
            ["Servers_SharedQuota"] = "All configs in this purchase share this quota.",
            ["Servers_Purchase1Details"] = "Purchase #1 — Details",
            ["Servers_Purchase2Details"] = "Purchase #2 — Details",
            ["Servers_PurchaseDetails"] = "Purchase #{0} — Details",
            ["Servers_Empty"] = "You have no active purchases yet. Buy a plan from the Plans page.",
            ["Servers_Tour1Title"] = "Your Subscriptions",
            ["Servers_Tour1Sub"] = "This card summarizes your plans — how many purchases are still active, how many locations you can use, and your total purchases.",
            ["Servers_Tour2Title"] = "A Purchase = One Plan",
            ["Servers_Tour2Sub"] = "Each purchase you made appears here. Tap the info button to see remaining data and time — all configs inside it share the same quota. Tap the card to expand.",
            ["Servers_Tour3Title"] = "Locations & Connect",
            ["Servers_Tour3Sub"] = "Expand a purchase to see one config per location. Tap Ping to measure latency, then Connect to route your traffic through that server.",

            // ── Account ──
            ["Account_ActiveSubscriptions"] = "Active Subscriptions",
            ["Account_NoSubs"] = "No active subscriptions. Purchase a plan to get started.",
            ["Account_DataLeft"] = "Data Left",
            ["Account_Expiry"] = "Expiry",
            ["Account_Locations"] = "Locations",
            ["Account_DataUsage"] = "Data Usage",
            ["Account_Section"] = "Account",
            ["Account_DaysLeftSuffix"] = "days left",
            ["Account_DaysSuffix"] = "Days",
            ["Account_SignOut"] = "Sign Out",
            ["Account_SignOutBtn"] = "Sign out",
            ["Account_SignOutDesc"] = "Sign out of your Lithium account",
            ["Account_DeleteAccount"] = "Delete Account",
            ["Account_DeleteBtn"] = "Delete",
            ["Account_DeleteDesc"] = "Permanently delete your account",
            ["Account_PlanPro"] = "Pro — 10GB — 1 Month",
            ["Account_PlanBasic"] = "Basic — 5GB — 1 Month",
            ["Account_47DaysLeft"] = "47 days left",
            ["Account_180DaysLeft"] = "180 days left",
            ["Account_47Days"] = "47 Days",
            ["Account_180Days"] = "180 Days",
            ["Account_Tour1Title"] = "Your Profile",
            ["Account_Tour1Sub"] = "This shows your account name and email address.",
            ["Account_Tour2Title"] = "Active Subscriptions",
            ["Account_Tour2Sub"] = "Each card shows one of your active plans — data left, days until expiry, and how many server locations are included.",
            ["Account_Tour3Title"] = "Account Actions",
            ["Account_Tour3Sub"] = "Use Sign Out to log off safely, or Delete Account to permanently remove your data.",
            ["Account_SignOutDialogTitle"] = "Sign Out",
            ["Account_SignOutDialogBody"] = "Are you sure you want to sign out?",
            ["Account_DeleteDialogTitle"] = "Delete Account",
            ["Account_DeleteDialogBody"] = "This action is permanent and cannot be undone. All your data, subscription, and coins will be lost.",
            ["Account_DeleteForever"] = "Delete Forever",

            // ── Coins ──
            ["Coins_LithiumCoins"] = "Lithium Coins",
            ["Coins_HowToBuy"] = "How to Buy Coins",
            ["Coins_Step1Title"] = "Contact Admin on Telegram",
            ["Coins_Step1Desc"] = "Message the admin and mention the coin amount you want",
            ["Coins_Step2Title"] = "Send Payment Receipt",
            ["Coins_Step2Desc"] = "After payment, send the receipt screenshot to the admin",
            ["Coins_Step3Title"] = "Coins Added to Your Account",
            ["Coins_Step3Desc"] = "After admin approval, coins appear in your balance automatically",
            ["Coins_ContactAdmin"] = "Contact Admin",
            ["Coins_TelegramAdmin"] = "Telegram Admin",
            ["Coins_CopyId"] = "Copy ID",
            ["Coins_OpenInTelegram"] = "Open in Telegram",
            ["Coins_Tour1Title"] = "Your Coin Balance",
            ["Coins_Tour1Sub"] = "This shows your current Lithium Coins — the in-app currency used to purchase VPN plans.",
            ["Coins_Tour2Title"] = "How to Buy Coins",
            ["Coins_Tour2Sub"] = "Follow these 3 steps: contact the admin on Telegram, send your payment receipt, and coins will be added after approval.",
            ["Coins_Tour3Title"] = "Contact Admin",
            ["Coins_Tour3Sub"] = "Tap Copy to copy the admin Telegram ID, or Open to launch Telegram and start the conversation directly.",
            ["Coins_CopiedToast"] = "Admin ID copied to clipboard",

            // ── Plans ──
            ["Plans_YourBalance"] = "Your balance",
            ["Plans_Coins"] = "Coins",
            ["Plans_ChooseAPlan"] = "Choose a Plan",
            ["Plans_Basic"] = "Basic",
            ["Plans_BasicDesc"] = "Great for light browsing",
            ["Plans_Pro"] = "Pro",
            ["Plans_ProDesc"] = "Best value for daily use",
            ["Plans_Ultimate"] = "Ultimate",
            ["Plans_UltimateDesc"] = "For heavy streaming & downloads",
            ["Plans_MostPopular"] = "MOST POPULAR",
            ["Plans_CoinsUnit"] = "coins",
            ["Plans_Per30Days"] = "/ 30 days",
            ["Plans_Per90Days"] = "/ 90 days",
            ["Plans_5gb"] = "5 GB data",
            ["Plans_50gb"] = "50 GB data",
            ["Plans_200gb"] = "200 GB data",
            ["Plans_30dValidity"] = "30 days validity",
            ["Plans_90dValidity"] = "90 days validity",
            ["Plans_5loc"] = "5 server locations",
            ["Plans_12loc"] = "12 server locations",
            ["Plans_AllLoc"] = "All server locations",
            ["Plans_Up2Devices"] = "Up to 2 devices",
            ["Plans_Up5Devices"] = "Up to 5 devices",
            ["Plans_Up10Devices"] = "Up to 10 devices",
            ["Plans_UnlimitedSpeed"] = "Unlimited speed",
            ["Plans_BuyBasic"] = "Buy with 450 coins",
            ["Plans_BuyPro"] = "Buy with 900 coins",
            ["Plans_BuyUltimate"] = "Buy with 2,200 coins",
            ["Plans_Tour1Title"] = "Your Coin Balance",
            ["Plans_Tour1Sub"] = "Plans are purchased with Lithium Coins. This shows how many coins you currently have available.",
            ["Plans_Tour2Title"] = "Pick a Plan",
            ["Plans_Tour2Sub"] = "Each plan shows its data, validity, locations and price. Compare them and choose the one that fits your needs.",
            ["Plans_Tour3Title"] = "Buy a Plan",
            ["Plans_Tour3Sub"] = "Tap Buy to purchase a plan with your coins. It will be added as a new subscription you can use on the Configs page.",
            ["Plans_Empty"] = "No plans are available right now.",
            ["Plans_CardSubtitle"] = "{0} GB · {1} mo",
            ["Plans_PricePerMonths"] = "/ {0} mo",
            ["Plans_FeatureData"] = "{0} GB data",
            ["Plans_FeatureValidityMonths"] = "{0}-month validity",
            ["Plans_FeatureLocations"] = "{0} server locations",
            ["Plans_FeatureDevices"] = "Up to {0} devices",
            ["Plans_BuyWithCoins"] = "Buy with {0} coins",
            ["Plans_NotEnoughTitle"] = "Not enough coins",
            ["Plans_NotEnoughBody"] = "The {0} plan costs {1} coins, but your balance is {2}. Buy more coins from the Coins page.",
            ["Plans_BuyTitle"] = "Buy {0} plan",
            ["Plans_BuyBody"] = "This will deduct {0} coins from your balance of {1}. Continue?",
            ["Plans_BuyConfirm"] = "Buy now",
            ["Plans_PurchasedToast"] = "{0} plan purchased successfully!",

            // ── Notifications ──
            ["Notif_Title"] = "Notifications",
            ["Notif_Empty"] = "You have no notifications yet.",

            // ── Splash ──
            ["Splash_ErrorTitle"] = "Connection Problem",
            ["Splash_ErrorBody"] = "We couldn't reach the server. Please check your internet connection and try again.",
            ["Splash_Retry"] = "Try Again",

            // ── Help ──
            ["Help_Title"] = "Help & Tour Guide",
            ["Help_Subtitle"] = "Select a section to start an interactive tour.",
            ["Help_StartTour"] = "Start Tour",
            ["Help_DashboardDesc"] = "Connect to VPN, view stats and manage your active config.",
            ["Help_ConfigsDesc"] = "Browse and select VPN server configurations.",
            ["Help_AccountDesc"] = "View and manage your account details and subscription.",
            ["Help_CoinsDesc"] = "Check your coin balance and earn more through referrals.",
            ["Help_PlansDesc"] = "Explore and purchase subscription plans.",
            ["Help_SupportTitle"] = "Support Tickets",
            ["Help_SupportSubtitle"] = "Have a problem? Open a ticket and chat with our team.",
            ["Help_NewTicket"] = "New Ticket",
            ["Help_NoTickets"] = "You have no tickets yet.",
            ["Help_TicketSubjectPlaceholder"] = "Briefly describe your issue",
            ["Help_Create"] = "Create",
            ["Help_TypeMessage"] = "Type a message…",
            ["Help_ActionFailed"] = "Something went wrong. Please try again.",

            // ── Login ──
            ["Login_WelcomeBack"] = "Welcome Back",
            ["Login_SignInSub"] = "Sign in to your Lithium account",
            ["Login_Username"] = "Username",
            ["Login_EnterUsername"] = "Enter username",
            ["Login_Password"] = "Password",
            ["Login_EnterPassword"] = "Enter password",
            ["Login_SignIn"] = "Sign In",
            ["Login_NoAccount"] = "Don't have an account?",
            ["Login_CreateOne"] = "Create one",
            ["Login_CreateAccount"] = "Create Account",
            ["Login_StepInfo"] = "Info",
            ["Login_StepVerify"] = "Verify",
            ["Login_StepDone"] = "Done",
            ["Login_ChooseUsername"] = "Choose a username",
            ["Login_Email"] = "Email",
            ["Login_EmailPlaceholder"] = "your@email.com",
            ["Login_CreatePassword"] = "Create a strong password",
            ["Login_ConfirmPassword"] = "Confirm Password",
            ["Login_RepeatPassword"] = "Repeat your password",
            ["Login_PasswordMust"] = "Password must:",
            ["Login_Rule8Chars"] = "Be at least 8 characters",
            ["Login_RuleDigit"] = "Contain at least one digit",
            ["Login_Continue"] = "Continue →",
            ["Login_CheckEmail"] = "Check your email",
            ["Login_Back"] = "← Back",
            ["Login_ResendCode"] = "Resend code",
            ["Login_VerifyCode"] = "Verify Code",
            ["Login_AccountCreated"] = "Your account has been created successfully!",
            ["Login_OtpHint"] = "We sent a 6-digit code to {0}",
            ["Login_WelcomeUser"] = "Welcome, {0}!",
            ["Login_OpeningApp"] = "Opening app in {0}s...",
            ["Login_InvalidCredentials"] = "Invalid username or password.",
            ["Login_FillAllFields"] = "Please fill in all fields.",
            ["Login_InvalidEmail"] = "Invalid email address.",
            ["Login_PasswordsNoMatch"] = "Passwords do not match.",
            ["Login_CodeResent"] = "A new verification code has been sent to your email.",
            ["Login_InvalidCode"] = "Invalid code. (hint: {0})",
            ["Login_GenericError"] = "Something went wrong. Please try again.",
            ["Login_LoadDataFailed"] = "Signed in, but we couldn't load your data. Please try again.",
            ["Login_EnterFullCode"] = "Please enter the full 6-digit code.",

            // ── Config selection dialog ──
            ["Dialog_SelectConfig"] = "Select Config",
            ["Dialog_Unavailable"] = "Unavailable",
            ["Dialog_ExpiryPrefix"] = "Expiry",
            ["Dialog_Purchase"] = "Purchase #{0}",
            ["Dialog_ImportedConfigs"] = "My Configs",
            ["Dialog_LocalConfig"] = "Personal config",

            // ── Offline / reconnect ──
            ["Offline_Title"] = "Can't reach the server",
            ["Offline_Body"] = "We couldn't connect to the backend. This page needs a connection. Check your internet and try again.",
            ["Offline_Reconnect"] = "Reconnect",
            ["Offline_HelpBody"] = "Support tickets need a connection to the server. Reconnect to view and reply to your tickets.",
            ["Offline_NotifBody"] = "Notifications need a connection to the server. Reconnect to see your latest updates.",
            ["Offline_ConfigsBody"] = "You have no imported configs yet, and the server can't be reached. Add your own config from the clipboard, or try reconnecting.",

            // ── Imported / local configs (Configs page) ──
            ["Configs_ImportedTitle"] = "My Configs",
            ["Configs_ImportedSubtitle"] = "Configs you imported yourself — always available, even offline.",
            ["Configs_BackendTitle"] = "Purchased Configs",
            ["Configs_AddFromClipboard"] = "Add from clipboard",
            ["Configs_ImportEmpty"] = "No imported configs yet. Copy a config link (or subscription) and add it.",
            ["Configs_ImportedNone"] = "Nothing on the clipboard could be imported. Copy a valid config link and try again.",
            ["Configs_ImportedOk"] = "Imported {0} config(s).",
            ["Configs_ImportedSome"] = "Imported {0} config(s); {1} skipped.",
            ["Configs_Rename"] = "Rename",
            ["Configs_Delete"] = "Delete",
            ["Configs_RenameTitle"] = "Rename config",
            ["Configs_DeleteTitle"] = "Delete config",
            ["Configs_DeleteBody"] = "Remove \"{0}\" from your imported configs?",
            ["Configs_NamePlaceholder"] = "Config name",
        };

        public static readonly Dictionary<string, string> Fa = new()
        {
            // ── Navigation ──
            ["Nav_Dashboard"] = "داشبورد",
            ["Nav_Configs"] = "کانفیگ‌ها",
            ["Nav_Account"] = "حساب کاربری",
            ["Nav_Coins"] = "سکه‌ها",
            ["Nav_Plans"] = "پلن‌ها",
            ["Nav_HelpTooltip"] = "راهنما و تورها",

            // ── Common ──
            ["Common_Next"] = "بعدی ‹",
            ["Common_SkipTour"] = "رد کردن",
            ["Common_Done"] = "تمام ✓",
            ["Common_GotIt"] = "متوجه شدم",
            ["Common_Cancel"] = "انصراف",
            ["Common_OK"] = "باشه",
            ["Common_Connect"] = "اتصال",
            ["Common_Ping"] = "پینگ",
            ["Common_TestPing"] = "تست پینگ",
            ["Common_Pinging"] = "در حال پینگ…",
            ["Common_Open"] = "باز کردن",

            // ── System tray ──
            ["Tray_Open"] = "باز کردن LithiumVPN",
            ["Tray_Disconnect"] = "قطع اتصال",
            ["Tray_Exit"] = "خروج",

            // ── Countries ──
            ["Country_Netherlands"] = "هلند",
            ["Country_Germany"] = "آلمان",
            ["Country_Poland"] = "لهستان",

            // ── Settings ──
            ["Settings_Appearance"] = "ظاهر",
            ["Settings_AppTheme"] = "پوسته برنامه",
            ["Settings_ThemeDesc"] = "پوسته رنگی دلخواهت رو انتخاب کن",
            ["Settings_ThemeLight"] = "روشن",
            ["Settings_ThemeDark"] = "تیره",
            ["Settings_ThemeSystem"] = "سیستم",
            ["Settings_WindowEffect"] = "افکت پنجره",
            ["Settings_WindowEffectDesc"] = "افکت پس‌زمینه پنجره رو انتخاب کن",
            ["Settings_EffectMatte"] = "مات",
            ["Settings_EffectHighMatte"] = "مات پررنگ",
            ["Settings_EffectGlass"] = "شیشه‌ای",
            ["Settings_EffectGlassThin"] = "شیشه‌ای نازک",
            ["Settings_LanguageSection"] = "زبان و منطقه",
            ["Settings_Language"] = "زبان",
            ["Settings_LanguageDesc"] = "زبان نمایش دلخواهت رو انتخاب کن",
            ["Settings_LanguageEnglish"] = "English",
            ["Settings_LanguagePersian"] = "فارسی",

            // ── Proxy exceptions ──
            ["Settings_ProxySection"] = "استثناهای پروکسی",
            ["Settings_ProxyExceptions"] = "لیست عبور مستقیم",
            ["Settings_ProxyExceptionsDesc"] = "دامنه‌ها یا آدرس‌هایی که اینجا اضافه می‌کنی از تانل VPN عبور نمی‌کنن و مستقیم وصل می‌شن. الگوهایی مثل *.example.com پشتیبانی می‌شن. تغییرات هنگام اتصال بلافاصله اعمال می‌شن.",
            ["Settings_ProxyAddPlaceholder"] = "مثلاً *.mydomain.com یا 192.168.1.5",
            ["Settings_ProxyAdd"] = "افزودن",
            ["Settings_ProxyEmpty"] = "هنوز استثنایی نیست. همه‌چیز از تانل عبور می‌کنه.",
            ["Settings_ProxyEdit"] = "ویرایش",
            ["Settings_ProxyDelete"] = "حذف",
            ["Settings_ProxySave"] = "ذخیره",
            ["Settings_ProxyCancel"] = "انصراف",
            ["Settings_ProxyDuplicate"] = "این مورد از قبل وجود داره.",

            // ── Dashboard ──
            ["Dash_GbLeft"] = "گیگ باقی‌مانده",
            ["Dash_Expiry"] = "انقضا",
            ["Dash_DaysLeft"] = "روز باقی‌مانده",
            ["Dash_Ping"] = "پینگ",
            ["Dash_Upload"] = "آپلود",
            ["Dash_Download"] = "دانلود",
            ["Dash_ChooseConfig"] = "کانفیگت رو انتخاب کن",
            ["Dash_NoConfigSelected"] = "کانفیگی انتخاب نشده",
            ["Dash_Tour1Title"] = "کانفیگ سرور",
            ["Dash_Tour1Sub"] = "این بخش سرور VPN انتخاب‌شده‌ی فعلی رو نشون می‌ده. برای تغییر سرور روی دکمه‌ی فلش بزن.",
            ["Dash_Tour2Title"] = "دکمه اتصال",
            ["Dash_Tour2Sub"] = "برای اتصال یا قطع اتصال VPN روی این دکمه بزن. وقتی متصل بشی سبز می‌شه.",
            ["Dash_Tour3Title"] = "آمار اتصال",
            ["Dash_Tour3Sub"] = "این کارت‌ها حجم باقی‌مانده، روزهای مونده تا انقضا، پینگ فعلی و سرعت آپلود/دانلود رو نشون می‌دن.",
            ["Dash_SelectConfigFirst"] = "اول یک کانفیگ انتخاب کن، بعد وصل شو.",
            ["Dash_ConnectFailed"] = "اتصال ناموفق بود: {0}",
            ["Dash_ConnectionLost"] = "اتصال قطع شد.",
            ["Dash_SpeedTest"] = "تست سرعت",
            ["Dash_SpeedTestNeedsConnection"] = "برای تست سرعت اول به VPN وصل شو.",
            ["Dash_SpeedTestUsesData"] = "توجه: تست سرعت بخشی از حجم اشتراکت رو مصرف می‌کنه.",

            // ── Servers / Configs ──
            ["Servers_Subscriptions"] = "اشتراک‌ها",
            ["Servers_Active"] = "فعال",
            ["Servers_Locations"] = "موقعیت‌ها",
            ["Servers_Purchases"] = "خریدها",
            ["Servers_Purchase1"] = "خرید ۱#",
            ["Servers_Purchase2"] = "خرید ۲#",
            ["Servers_PlanDetails"] = "جزئیات پلن",
            ["Servers_DataLeft"] = "حجم باقی‌مانده",
            ["Servers_TimeLeft"] = "زمان باقی‌مانده",
            ["Servers_SharedQuota"] = "همه‌ی کانفیگ‌های این خرید از یک سهمیه‌ی مشترک استفاده می‌کنن.",
            ["Servers_Purchase1Details"] = "خرید ۱# — جزئیات",
            ["Servers_Purchase2Details"] = "خرید ۲# — جزئیات",
            ["Servers_PurchaseDetails"] = "خرید {0}# — جزئیات",
            ["Servers_Empty"] = "هنوز خرید فعالی نداری. از صفحه‌ی پلن‌ها یک پلن بخر.",
            ["Servers_Tour1Title"] = "اشتراک‌های تو",
            ["Servers_Tour1Sub"] = "این کارت خلاصه‌ای از پلن‌هات می‌ده — چند خرید هنوز فعاله، چند موقعیت می‌تونی استفاده کنی و مجموع خریدهات.",
            ["Servers_Tour2Title"] = "هر خرید = یک پلن",
            ["Servers_Tour2Sub"] = "هر خریدی که انجام دادی اینجا میاد. روی دکمه‌ی اطلاعات بزن تا حجم و زمان باقی‌مانده رو ببینی — همه‌ی کانفیگ‌های داخلش از یک سهمیه استفاده می‌کنن. برای باز شدن روی کارت بزن.",
            ["Servers_Tour3Title"] = "موقعیت‌ها و اتصال",
            ["Servers_Tour3Sub"] = "یک خرید رو باز کن تا برای هر موقعیت یک کانفیگ ببینی. روی پینگ بزن تا تأخیر اندازه‌گیری بشه، بعد روی اتصال بزن تا ترافیکت از اون سرور عبور کنه.",

            // ── Account ──
            ["Account_ActiveSubscriptions"] = "اشتراک‌های فعال",
            ["Account_NoSubs"] = "اشتراک فعالی نداری. برای شروع یک پلن بخر.",
            ["Account_DataLeft"] = "حجم باقی‌مانده",
            ["Account_Expiry"] = "انقضا",
            ["Account_Locations"] = "موقعیت‌ها",
            ["Account_DataUsage"] = "مصرف حجم",
            ["Account_Section"] = "حساب کاربری",
            ["Account_DaysLeftSuffix"] = "روز باقی‌مانده",
            ["Account_DaysSuffix"] = "روز",
            ["Account_SignOut"] = "خروج از حساب",
            ["Account_SignOutBtn"] = "خروج",
            ["Account_SignOutDesc"] = "از حساب لیتیوم خودت خارج شو",
            ["Account_DeleteAccount"] = "حذف حساب",
            ["Account_DeleteBtn"] = "حذف",
            ["Account_DeleteDesc"] = "حساب کاربریت رو برای همیشه حذف کن",
            ["Account_PlanPro"] = "Pro — ۱۰ گیگ — ۱ ماه",
            ["Account_PlanBasic"] = "Basic — ۵ گیگ — ۱ ماه",
            ["Account_47DaysLeft"] = "۴۷ روز باقی‌مانده",
            ["Account_180DaysLeft"] = "۱۸۰ روز باقی‌مانده",
            ["Account_47Days"] = "۴۷ روز",
            ["Account_180Days"] = "۱۸۰ روز",
            ["Account_Tour1Title"] = "پروفایل تو",
            ["Account_Tour1Sub"] = "این بخش نام و ایمیل حسابت رو نشون می‌ده.",
            ["Account_Tour2Title"] = "اشتراک‌های فعال",
            ["Account_Tour2Sub"] = "هر کارت یکی از پلن‌های فعالت رو نشون می‌ده — حجم باقی‌مانده، روزهای مونده تا انقضا و تعداد موقعیت‌های سرور.",
            ["Account_Tour3Title"] = "عملیات حساب",
            ["Account_Tour3Sub"] = "برای خروج امن از «خروج از حساب» و برای حذف دائمی داده‌هات از «حذف حساب» استفاده کن.",
            ["Account_SignOutDialogTitle"] = "خروج از حساب",
            ["Account_SignOutDialogBody"] = "مطمئنی می‌خوای خارج بشی؟",
            ["Account_DeleteDialogTitle"] = "حذف حساب",
            ["Account_DeleteDialogBody"] = "این کار دائمی‌ست و قابل بازگشت نیست. همه‌ی داده‌ها، اشتراک و سکه‌هات از بین می‌رن.",
            ["Account_DeleteForever"] = "حذف برای همیشه",

            // ── Coins ──
            ["Coins_LithiumCoins"] = "سکه‌های لیتیوم",
            ["Coins_HowToBuy"] = "چطور سکه بخریم",
            ["Coins_Step1Title"] = "تماس با ادمین در تلگرام",
            ["Coins_Step1Desc"] = "به ادمین پیام بده و مقدار سکه‌ای که می‌خوای رو بگو",
            ["Coins_Step2Title"] = "ارسال رسید پرداخت",
            ["Coins_Step2Desc"] = "بعد از پرداخت، اسکرین‌شات رسید رو برای ادمین بفرست",
            ["Coins_Step3Title"] = "سکه‌ها به حسابت اضافه شد",
            ["Coins_Step3Desc"] = "بعد از تأیید ادمین، سکه‌ها به‌صورت خودکار به موجودیت اضافه می‌شن",
            ["Coins_ContactAdmin"] = "تماس با ادمین",
            ["Coins_TelegramAdmin"] = "ادمین تلگرام",
            ["Coins_CopyId"] = "کپی آیدی",
            ["Coins_OpenInTelegram"] = "باز کردن در تلگرام",
            ["Coins_Tour1Title"] = "موجودی سکه‌ی تو",
            ["Coins_Tour1Sub"] = "این بخش سکه‌های لیتیوم فعلیت رو نشون می‌ده — واحد پول داخل برنامه برای خرید پلن‌های VPN.",
            ["Coins_Tour2Title"] = "چطور سکه بخریم",
            ["Coins_Tour2Sub"] = "این ۳ مرحله رو دنبال کن: با ادمین در تلگرام تماس بگیر، رسید پرداختت رو بفرست و سکه‌ها بعد از تأیید اضافه می‌شن.",
            ["Coins_Tour3Title"] = "تماس با ادمین",
            ["Coins_Tour3Sub"] = "برای کپی آیدی تلگرام ادمین روی «کپی» و برای باز کردن تلگرام و شروع گفتگو روی «باز کردن» بزن.",
            ["Coins_CopiedToast"] = "آیدی ادمین در کلیپ‌بورد کپی شد",

            // ── Plans ──
            ["Plans_YourBalance"] = "موجودی تو",
            ["Plans_Coins"] = "سکه",
            ["Plans_ChooseAPlan"] = "یک پلن انتخاب کن",
            ["Plans_Basic"] = "پایه",
            ["Plans_BasicDesc"] = "مناسب برای گشت‌وگذار سبک",
            ["Plans_Pro"] = "حرفه‌ای",
            ["Plans_ProDesc"] = "بهترین انتخاب برای استفاده‌ی روزانه",
            ["Plans_Ultimate"] = "نامحدود",
            ["Plans_UltimateDesc"] = "برای استریم و دانلود سنگین",
            ["Plans_MostPopular"] = "محبوب‌ترین",
            ["Plans_CoinsUnit"] = "سکه",
            ["Plans_Per30Days"] = "/ ۳۰ روز",
            ["Plans_Per90Days"] = "/ ۹۰ روز",
            ["Plans_5gb"] = "۵ گیگ حجم",
            ["Plans_50gb"] = "۵۰ گیگ حجم",
            ["Plans_200gb"] = "۲۰۰ گیگ حجم",
            ["Plans_30dValidity"] = "۳۰ روز اعتبار",
            ["Plans_90dValidity"] = "۹۰ روز اعتبار",
            ["Plans_5loc"] = "۵ موقعیت سرور",
            ["Plans_12loc"] = "۱۲ موقعیت سرور",
            ["Plans_AllLoc"] = "همه‌ی موقعیت‌های سرور",
            ["Plans_Up2Devices"] = "تا ۲ دستگاه",
            ["Plans_Up5Devices"] = "تا ۵ دستگاه",
            ["Plans_Up10Devices"] = "تا ۱۰ دستگاه",
            ["Plans_UnlimitedSpeed"] = "سرعت نامحدود",
            ["Plans_BuyBasic"] = "خرید با ۴۵۰ سکه",
            ["Plans_BuyPro"] = "خرید با ۹۰۰ سکه",
            ["Plans_BuyUltimate"] = "خرید با ۲٬۲۰۰ سکه",
            ["Plans_Tour1Title"] = "موجودی سکه‌ی تو",
            ["Plans_Tour1Sub"] = "پلن‌ها با سکه‌های لیتیوم خریداری می‌شن. این بخش نشون می‌ده چند سکه در دسترس داری.",
            ["Plans_Tour2Title"] = "یک پلن انتخاب کن",
            ["Plans_Tour2Sub"] = "هر پلن حجم، اعتبار، موقعیت‌ها و قیمتش رو نشون می‌ده. مقایسه کن و اونی که به نیازت می‌خوره رو انتخاب کن.",
            ["Plans_Tour3Title"] = "خرید یک پلن",
            ["Plans_Tour3Sub"] = "روی «خرید» بزن تا با سکه‌هات یک پلن بخری. به‌عنوان یک اشتراک جدید اضافه می‌شه که می‌تونی در صفحه‌ی کانفیگ‌ها ازش استفاده کنی.",
            ["Plans_Empty"] = "در حال حاضر پلنی موجود نیست.",
            ["Plans_CardSubtitle"] = "{0} گیگ · {1} ماه",
            ["Plans_PricePerMonths"] = "/ {0} ماه",
            ["Plans_FeatureData"] = "{0} گیگ حجم",
            ["Plans_FeatureValidityMonths"] = "{0} ماه اعتبار",
            ["Plans_FeatureLocations"] = "{0} موقعیت سرور",
            ["Plans_FeatureDevices"] = "تا {0} دستگاه",
            ["Plans_BuyWithCoins"] = "خرید با {0} سکه",
            ["Plans_NotEnoughTitle"] = "سکه کافی نیست",
            ["Plans_NotEnoughBody"] = "پلن {0} قیمتش {1} سکه‌ست، اما موجودی تو {2} سکه‌ست. از صفحه‌ی سکه‌ها سکه‌ی بیشتری بخر.",
            ["Plans_BuyTitle"] = "خرید پلن {0}",
            ["Plans_BuyBody"] = "این کار {0} سکه از موجودی {1} سکه‌ای تو کم می‌کنه. ادامه می‌دی؟",
            ["Plans_BuyConfirm"] = "خرید",
            ["Plans_PurchasedToast"] = "پلن {0} با موفقیت خریداری شد!",

            // ── Notifications ──
            ["Notif_Title"] = "اعلان‌ها",
            ["Notif_Empty"] = "هنوز اعلانی نداری.",

            // ── Splash ──
            ["Splash_ErrorTitle"] = "مشکل در اتصال",
            ["Splash_ErrorBody"] = "نتونستیم به سرور وصل بشیم. لطفاً اتصال اینترنتت رو بررسی کن و دوباره تلاش کن.",
            ["Splash_Retry"] = "تلاش دوباره",

            // ── Help ──
            ["Help_Title"] = "راهنما و تور",
            ["Help_Subtitle"] = "برای شروع تور تعاملی یک بخش رو انتخاب کن.",
            ["Help_StartTour"] = "شروع تور",
            ["Help_DashboardDesc"] = "به VPN وصل شو، آمار رو ببین و کانفیگ فعالت رو مدیریت کن.",
            ["Help_ConfigsDesc"] = "کانفیگ‌های سرور VPN رو مرور و انتخاب کن.",
            ["Help_AccountDesc"] = "جزئیات حساب و اشتراکت رو ببین و مدیریت کن.",
            ["Help_CoinsDesc"] = "موجودی سکه‌ت رو ببین و با معرفی دوستان بیشتر به‌دست بیار.",
            ["Help_PlansDesc"] = "پلن‌های اشتراک رو ببین و خریداری کن.",
            ["Help_SupportTitle"] = "تیکت‌های پشتیبانی",
            ["Help_SupportSubtitle"] = "مشکلی داری؟ یک تیکت باز کن و با تیم ما گفتگو کن.",
            ["Help_NewTicket"] = "تیکت جدید",
            ["Help_NoTickets"] = "هنوز تیکتی نداری.",
            ["Help_TicketSubjectPlaceholder"] = "مشکلت رو کوتاه توضیح بده",
            ["Help_Create"] = "ایجاد",
            ["Help_TypeMessage"] = "یک پیام بنویس…",
            ["Help_ActionFailed"] = "یه مشکلی پیش اومد. لطفاً دوباره تلاش کن.",

            // ── Login ──
            ["Login_WelcomeBack"] = "خوش اومدی",
            ["Login_SignInSub"] = "به حساب لیتیوم خودت وارد شو",
            ["Login_Username"] = "نام کاربری",
            ["Login_EnterUsername"] = "نام کاربری رو وارد کن",
            ["Login_Password"] = "رمز عبور",
            ["Login_EnterPassword"] = "رمز عبور رو وارد کن",
            ["Login_SignIn"] = "ورود",
            ["Login_NoAccount"] = "حساب کاربری نداری؟",
            ["Login_CreateOne"] = "یکی بساز",
            ["Login_CreateAccount"] = "ساخت حساب",
            ["Login_StepInfo"] = "اطلاعات",
            ["Login_StepVerify"] = "تأیید",
            ["Login_StepDone"] = "پایان",
            ["Login_ChooseUsername"] = "یک نام کاربری انتخاب کن",
            ["Login_Email"] = "ایمیل",
            ["Login_EmailPlaceholder"] = "your@email.com",
            ["Login_CreatePassword"] = "یک رمز عبور قوی بساز",
            ["Login_ConfirmPassword"] = "تکرار رمز عبور",
            ["Login_RepeatPassword"] = "رمز عبور رو دوباره وارد کن",
            ["Login_PasswordMust"] = "رمز عبور باید:",
            ["Login_Rule8Chars"] = "حداقل ۸ کاراکتر باشه",
            ["Login_RuleDigit"] = "حداقل یک عدد داشته باشه",
            ["Login_Continue"] = "ادامه →",
            ["Login_CheckEmail"] = "ایمیلت رو چک کن",
            ["Login_Back"] = "→ بازگشت",
            ["Login_ResendCode"] = "ارسال مجدد کد",
            ["Login_VerifyCode"] = "تأیید کد",
            ["Login_AccountCreated"] = "حساب کاربریت با موفقیت ساخته شد!",
            ["Login_OtpHint"] = "یک کد ۶ رقمی به {0} ارسال کردیم",
            ["Login_WelcomeUser"] = "خوش اومدی، {0}!",
            ["Login_OpeningApp"] = "باز شدن برنامه تا {0} ثانیه دیگه...",
            ["Login_InvalidCredentials"] = "نام کاربری یا رمز عبور نادرسته.",
            ["Login_FillAllFields"] = "لطفاً همه‌ی فیلدها رو پر کن.",
            ["Login_InvalidEmail"] = "آدرس ایمیل نامعتبره.",
            ["Login_PasswordsNoMatch"] = "رمزهای عبور یکی نیستن.",
            ["Login_CodeResent"] = "یک کد تأیید جدید به ایمیلت ارسال شد.",
            ["Login_InvalidCode"] = "کد نادرسته. (راهنما: {0})",
            ["Login_GenericError"] = "یه مشکلی پیش اومد. لطفاً دوباره تلاش کن.",
            ["Login_LoadDataFailed"] = "وارد شدی، اما نتونستیم داده‌هات رو بارگذاری کنیم. لطفاً دوباره تلاش کن.",
            ["Login_EnterFullCode"] = "لطفاً کد ۶ رقمی رو کامل وارد کن.",

            // ── Config selection dialog ──
            ["Dialog_SelectConfig"] = "انتخاب کانفیگ",
            ["Dialog_Unavailable"] = "در دسترس نیست",
            ["Dialog_ExpiryPrefix"] = "انقضا",
            ["Dialog_Purchase"] = "خرید {0}#",
            ["Dialog_ImportedConfigs"] = "کانفیگ‌های من",
            ["Dialog_LocalConfig"] = "کانفیگ شخصی",

            // ── Offline / reconnect ──
            ["Offline_Title"] = "اتصال به سرور برقرار نشد",
            ["Offline_Body"] = "نتونستیم به بک‌اند وصل بشیم. این صفحه به اتصال نیاز داره. اینترنتت رو بررسی کن و دوباره تلاش کن.",
            ["Offline_Reconnect"] = "اتصال دوباره",
            ["Offline_HelpBody"] = "تیکت‌های پشتیبانی به اتصال سرور نیاز دارن. برای دیدن و پاسخ به تیکت‌هات دوباره وصل شو.",
            ["Offline_NotifBody"] = "اعلان‌ها به اتصال سرور نیاز دارن. برای دیدن آخرین به‌روزرسانی‌ها دوباره وصل شو.",
            ["Offline_ConfigsBody"] = "هنوز کانفیگ ایمپورتی نداری و سرور هم در دسترس نیست. کانفیگ خودت رو از کلیپ‌بورد اضافه کن، یا دوباره تلاش کن وصل بشی.",

            // ── Imported / local configs (Configs page) ──
            ["Configs_ImportedTitle"] = "کانفیگ‌های من",
            ["Configs_ImportedSubtitle"] = "کانفیگ‌هایی که خودت اضافه کردی — همیشه در دسترسن، حتی آفلاین.",
            ["Configs_BackendTitle"] = "کانفیگ‌های خریداری‌شده",
            ["Configs_AddFromClipboard"] = "افزودن از کلیپ‌بورد",
            ["Configs_ImportEmpty"] = "هنوز کانفیگ ایمپورتی نداری. یک لینک کانفیگ (یا ساب) کپی کن و اضافه‌ش کن.",
            ["Configs_ImportedNone"] = "چیزی توی کلیپ‌بورد قابل افزودن نبود. یک لینک کانفیگ معتبر کپی کن و دوباره امتحان کن.",
            ["Configs_ImportedOk"] = "{0} کانفیگ اضافه شد.",
            ["Configs_ImportedSome"] = "{0} کانفیگ اضافه شد؛ {1} مورد رد شد.",
            ["Configs_Rename"] = "تغییر نام",
            ["Configs_Delete"] = "حذف",
            ["Configs_RenameTitle"] = "تغییر نام کانفیگ",
            ["Configs_DeleteTitle"] = "حذف کانفیگ",
            ["Configs_DeleteBody"] = "«{0}» از کانفیگ‌های ایمپورتیت حذف بشه؟",
            ["Configs_NamePlaceholder"] = "نام کانفیگ",
        };
    }
}
